version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: convenia_swoole_api
    working_dir: /var/www/html/api
    volumes:
      - ./api:/var/www/html/api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
    depends_on:
      - mysql
    command: >
      bash -c "
      composer install && \
      cp .env.example .env && \
      php artisan l5-swagger:generate && \
      php artisan passport:client --personal && \
      php artisan key:generate && \
      if [ ! -f storage/oauth-private.key ]; then
        php artisan passport:keys
      fi && \
      php artisan migrate:status | grep -q 'Ran' || php artisan migrate:fresh --seed && \
      npm i && npm install chokidar && \
      php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --watch
      "

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: convenia
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
